__author__ = 'Mikhan Victor'
__email__ = 'victormikhan@gmail.com'
__package__ = 'rss-reader'
__version__ = '2.0.0'
__description__ = 'RSS Reader'
__url__ = 'https://github.com/victormikhan/PythonHomework'
