# Generated by Django 2.2.5 on 2019-11-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
