# Generated by Django 2.2.5 on 2019-11-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191115_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='pubDate',
            field=models.DateTimeField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
