# Generated by Django 2.2.5 on 2019-11-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsinfo_rss_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='rss_hash',
            field=models.CharField(default=-2587653717502456127, max_length=255),
        ),
    ]
