# Generated by Django 2.2.7 on 2019-11-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsinfo_rss_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='rss_hash',
            field=models.CharField(default=1867412579743329750, max_length=255),
        ),
    ]
