# Generated by Django 2.2.7 on 2019-11-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20191118_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsinfo',
            name='rss_image',
            field=models.CharField(default='image', max_length=255),
        ),
        migrations.AlterField(
            model_name='lastnewsinfo',
            name='rss_hash',
            field=models.CharField(default=-8682373561287484793, max_length=255),
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='rss_hash',
            field=models.CharField(default=-8682373561287484793, max_length=255),
        ),
    ]
