# Generated by Django 2.2.7 on 2019-11-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20191121_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastNewsInfo',
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='rss_hash',
            field=models.CharField(default=786337036574844709, max_length=255),
        ),
    ]
