# Generated by Django 2.2.7 on 2019-11-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20191126_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='imageDescription',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='rss_hash',
            field=models.CharField(default=8128866865693763069, max_length=255),
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='title_hash',
            field=models.CharField(default=-309102394326670342, max_length=255),
        ),
    ]
