# Generated by Django 2.2.5 on 2019-11-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20191126_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsinfo',
            name='rss_hash',
            field=models.CharField(default=978881250837751239, max_length=255),
        ),
        migrations.AlterField(
            model_name='newsinfo',
            name='title_hash',
            field=models.CharField(default=7488628369778039197, max_length=255),
        ),
    ]
